server:
  port: 9527
spring:
  profiles: dev #开发环境
  application:
    name: AIGOU-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
      instance-id: gateway-9527.com
      prefer-ip-address: true
zuul:
   routes:
      aigouUser.serviceId: user-provider
      aigouUser.path: /user/**
   ignored-services: "*"
   prefix: /aigou
---
server:
  port: 9528
spring:
  profiles: test #测试环境
  application:
    name: AIGOU-ZUUL-GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
      instance-id: gateway-9527.com
      prefer-ip-address: true
zuul:
   routes:
      aigouUser.serviceId: user-provider
      aigouUser.path: /user/**
   ignored-services: "*"
   prefix: /aigou
